### ISSUE TITLE
CORS Policy issue upon adding a new record from Roam to Zotero

### ISSUE THREAD

**Issue by gijigae** [greenmeen/zotero-roam#11]
Upon adding a new record from Roam to Zotero, I am seeing the following error message in the console. It will be really great if a reference record can be added to Zotero from Roam.

![zotero-cors-error](https://user-images.githubusercontent.com/81459/129327753-d5ea779f-467f-48d3-8630-59b830e89f67.jpg)

**Comment by greenmeen** [comment]
Looking at the target URL, the request failed because there was no target library selected. My guess is that the radio button for your library is disabled because your API key does not have the 'write' permission for your library.
Can you check that in your API key settings?

**Comment by gijigae** [comment]
Checked the setting and as you pointed out it was read-only. Granted write access and now it works like a charm. Thank you so much for the Zotero-to-Roam and the guidance!
