### ISSUE TITLE
Contextual button moves blocks to the left outside of clickable area

### ISSUE THREAD

**Issue by sebastianpech** [greenmeen/zotero-roam#12]
When the contextual button is visible, roam blocks are shifted to the left like in the following screenshot:

![image](https://user-images.githubusercontent.com/13043943/129752670-0eb64ffd-7b22-469a-8762-60fb2bc814ff.png)

**Comment by greenmeen** [comment]
I've flagged this but can't narrow down the specific cause... I could hack a fix but would like to investigate more & figure out why it's happening exactly before publishing a change. Adding to my TODOs!

**Comment by sebastianpech** [comment]
Btw. just tested this in a completely empty graph. Same behavior on 

ROAM VERSION:
0.8.8-394e628e

**Comment by greenmeen** [comment]
Hey @sebastianpech - I was able to reproduce the issue previously in my own graph, and was working on a fax, but after recent updates in Roam version I can't reproduct this behavior anymore.

Is this still happening for you ?

ROAM VERSION:
0.8.8-908838fd

**Comment by sebastianpech** [comment]
It's not happening on the DNP page directly, but if you are in the DNP overview, the issue is still there.

**Comment by IamMarek** [comment]
I can confirm this still hapenning on the daily page in ROAM VERSION: 0.8.8-ebc7098a

The `.zotero-roam-page-related{opacity:0.6;float:right;margin-top:-40px;}` css style is to blaim. Anything above -30px does the error. I suggest changing it to -30px.
