### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by gijigae** [greenmeen/zotero-roam#13]
Upon opening the "References" page, it shows the "Uncaught TypeError: Cannot convert undefined or null to object" message in the console (see the image below). The "Add to Zotero" button does not respond. What would be a possible cause?

![zotero-error](https://user-images.githubusercontent.com/81459/130425400-0793d219-d147-4cbd-8b81-5ac131767e76.jpg)

**Comment by greenmeen** [comment]
Thank you for uploading the console error! I think I've located it (missing check on the API key's group permissions), working on a fix now.

**Comment by gijigae** [comment]
Thanks for the quick update! For the time being, changed the group permission and everything is working as expected.
