### ISSUE TITLE
Code snippet in GitBook has a syntax error

### ISSUE THREAD

**Issue by abehr** [greenmeen/zotero-roam#15]
In section 3.3 of the GitBook ([Creating your own formatting functions](https://alix-lahuec.gitbook.io/zotero-roam/customization/formatting)), there is an example code snippet which replicates the default formatting function as a jumping off point for customization.

If you try to run that code directly as-is, you get a JS syntax error: `Invalid shorthand property initializer`. This is because on line 34 of the snippet, the params passed to `getLocalLink` and `getWebLink` are set with `=` instead of `:`. Replacing them resolves the error.

(sorry if this is the wrong place to post this issue, also this is barely an issue)

**Comment by greenmeen** [comment]
Thanks so much for flagging - definitely the right place! Corrected it a few weeks back, so I'll close this :)
