### ISSUE TITLE
Citekeys are different between roam research and local Better BibTeX

### ISSUE THREAD

**Issue by YKX-A** [greenmeen/zotero-roam#17]
If I'm not misunderstand, Zotero-roam uses synced `Citation Key` column in the local Zotero as the `citekey` in Roam.
However, in Roam:
![截屏2021-10-09 上午10 49 43](https://user-images.githubusercontent.com/38134733/136641487-2b6ae192-fb44-4628-8706-3dcdbd95f3cb.png)

In Zotero:
![截屏2021-10-09 上午10 50 39](https://user-images.githubusercontent.com/38134733/136641508-337968b5-8764-4fe9-a657-04ea7f9cd1ea.png)

**Comment by YKX-A** [comment]
Pin the citation key in Zotero and restart the js plugin works. That's my ignorance ......😂

**Comment by portgasray** [comment]
works for me, thank you
