### ISSUE TITLE
Fail to load resource

### ISSUE THREAD

**Issue by Xiaojun928** [greenmeen/zotero-roam#2]
Hi Alix,

Thanks a lot for the awesome project and amazing video!

After installing the zoteroRoam, the book icon of mine is always red, so I checked the browser console. It shows these details.  
![image](https://user-images.githubusercontent.com/24545157/114842757-bd23c900-9e0b-11eb-8d3c-91d4a0f4538c.png)

The "Data Syncing" of mine is the same as yours in the demo, while the "File Syncing" is through WebDAV, I am not sure if this is the cause. 
Could you please give me some suggestions? Thanks again!

Best,
Xiaojun

**Comment by greenmeen** [comment]
Hi there!
There's an issue with your data URI : you need to use your Zotero **user ID** (a 6-digit or 7-digit identifier) and not your username.

**Comment by Xiaojun928** [comment]
It works when using the user ID, Thanks a lot 😀

Cheers,
Xiaojun
