### ISSUE TITLE
[Suggestion] popup ui (for adding citations) is quite squished when not in full screen.

### ISSUE THREAD

**Issue by sooheon** [greenmeen/zotero-roam#20]
When roam is in half-screen width mode, the popups are egregiously skinny. When the viewport is only 750px, I don't mind if the popup is 700px wide. Min-width setting to something reasonable should fix it.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/302945/154410446-e190e1b5-02e1-4a3c-bc31-e905878fc923.png">

<img width="868" alt="image" src="https://user-images.githubusercontent.com/302945/154410531-5cd10045-7fc8-432e-8e42-7522eab189c9.png">

**Comment by sooheon** [comment]
Customized with following roam/css block. Feel free to close.

```
.zotero-roam-dialog-overlay [side-panel="hidden"] {
  width: calc(100% - 10vw) !important;
}
.zotero-roam-dialog-overlay > .bp3-dialog-container > .bp3-dialog {
  margin-left: calc(5vw) !important;
}

.zotero-roam-dialog-small [side-panel="hidden"] {
  width: calc(100% - 10vw) !important;
}

.zotero-roam-dialog-small .bp3-dialog {
  margin-left: calc(5vw) !important;
}
```

<img width="867" alt="image" src="https://user-images.githubusercontent.com/302945/154415762-4329c97f-e79d-42d3-a0ae-7f7aae074e37.png">

**Comment by greenmeen** [comment]
Thanks - adding to next major release!
