### ISSUE TITLE
Changing metadata of imported roam pages 

### ISSUE THREAD

**Issue by merttoka** [greenmeen/zotero-roam#4]
Hi, thanks for the awesome integration. I love it.

I was wondering if we can remove the attributes from a Zotero import. For example, instead of `Title::` it can simply use `Title:`. This way, the imports won't clutter the graph with many nodes and exponentially many edges. I understand that some people actually like this functionality, so an option at the import page would be even more awesome.

If I understand from issue #3, it's not easy to modify existing items, but I can clear them manually if new items aren't added with these attributes.

**Comment by greenmeen** [comment]
Hi there!
If you'd like to change how the metadata is imported, you can write your own formatting function. The default formatting is really only meant to serve as a starting point - as metadata organization is a very personal thing. Some folks use flat templates, some nest information, some use soft line breaks, everyone uses different attribute names, etc. 

Let me know if I can help with this, I know writing JavaScript functions can be a bit of a step!

(and yes, updating templates just isn't possible with Roam's outline setup)

**Comment by merttoka** [comment]
Thanks for the reply. 
Writing JS functions is not a problem. If I understand correctly only [this function ](https://github.com/greenmeen/zotero-roam/blob/7bca954736ef98fe589b16455c720c9b900e0d6b/src/formatting.js#L99) needs updating. However, I don't know how to put the modified function in my instance of zotero-roam. The first thing that comes to mind is replacing the minimized function directly in the source:

```
var s = document.createElement("script");
s.src = "https://cdn.jsdelivr.net/npm/@alixlahuec/zotero-roam@0.5";

// replace 'getItemMetaData' in 's.src' with a custom version here
// getItemMetadata(e){let t=[];e.data.title&&t.push(`Title:: ${e.data.title}`),0<e.data.creators.length&&t.push(`Author(s):: ${zoteroRoam.formatting.getCreators(e)}`),e.data.abstractNote&&t.push(`Abstract:: ${e.data.abstractNote}`),e.data.itemType&&t.push(`Type:: [[${zoteroRoam.formatting.getItemType(e)}]]`),t.push(`Publication:: ${e.data.publicationTitle||e.data.bookTitle||""}`),e.data.url&&t.push(`URL : ${e.data.url}`),e.data.dateAdded&&t.push(`Date Added:: ${zoteroRoam.utils.makeDNP(e.data.dateAdded,{brackets:!0})}`),t.push(`Zotero links:: ${zoteroRoam.formatting.getLocalLink(e)}, ${zoteroRoam.formatting.getWebLink(e)}`),0<e.data.tags.length&&t.push(`Tags:: ${zoteroRoam.formatting.getTags(e)}`);let o=zoteroRoam.formatting.getItemChildren(e,{pdf_as:"links",notes_as:"formatted",split_char:"\n"});if(o.pdfItems&&t.push(`PDF links : ${o.pdfItems.join(", ")}`),o.notes){let e={string:"[[Notes]]",children:[]};e.children.push(...o.notes.flat(1)),t.push(e)}return t}}

s.id = "zotero-roam";
s.type = "text/javascript";
document.getElementsByTagName("body")[0].appendChild(s);
```

Is there a neater way of doing this modification?

**Comment by greenmeen** [comment]
Yes there is - I'd suggest starting here : https://alix-lahuec.gitbook.io/zotero-roam/customization/formatting
It's a two-step process : 
1) writing a function in a roam/js code block, with syntax `window.functionName = function(item) {...}`
2) adding a `funcmap` object in the extension's settings. To use the function as default for all item types : `funcmap: {DEFAULT: "functionName"}`

(the default function is namespaced by the way! It's `zoteroRoam.formatting.getItemMetadata`)

**Comment by merttoka** [comment]
Aaah, I feel stupid that I didn't check the docs before asking the question. 

It works perfectly, thank you very much!
