### ISSUE TITLE
How to get the collection name of one item?

### ISSUE THREAD

**Issue by mgdreamingstar** [greenmeen/zotero-roam#5]
`zoteroRoam.data.collections` doesn't have the name of collections.

**Comment by greenmeen** [comment]
Hey!

`zoteroRoam.data.collections` contains the raw data for each collection, as returned by the Zotero API.  For each collection, the name should be under `data` then under `name`. 

See the information here : https://alix-lahuec.gitbook.io/zotero-roam/customization/formatting/code-snippets#getting-an-items-collections

Specifically : 
```
// To obtain an Array with the collections' names :
zoteroRoam.formatting.getItemCollections(item).map(collection => collection.data.name);
// Returns :
// ['Collection name', 'Other collection name']
```

**Comment by mgdreamingstar** [comment]
Hi, I noticed this snippets, but it doesn't work.

the `data` doesn't contain name of collections but only collections' id.

I tried to get collections' name using dataURI: "users/xxxxxxx/collections", but it seems that zoteroRoam can only make one data request.

**Comment by greenmeen** [comment]
You can make several data requests. But the extension retrieves collections information automatically, and keeps them separate under `zoteroRoam.data.collections`. Which is an Array with the full data for the collections. 
The item itself, under `data.collections`, will indeed have only the IDs - that's what the function is for, to use the collection IDs to get the names.
Do try it out, and if it doesn't get you what you're looking for, please post the code you're using 🙂

For import, you can add the notes separately now - rather than having to remove/reimport all the metadata.

**Comment by mgdreamingstar** [comment]
I tried this code `metadata.push(zoteroRoam.data.collections)` but it returns Array(0).
I use this uri `users/your_user_id/items` to make datarequest.

**Comment by greenmeen** [comment]
It should be something like `metadata.push(zoteroRoam.formatting.getItemCollections(item).map(c => c.data.name).join(", "))`.
It will add a block to your metadata array which contains the comma-separated list of the collection names the item belongs to.
(you can customize this of course, to have an attribute, a different separating character, surround with brackets, etc.)

What's important when adding elements to the metadata array is that they're of the right format (either a string of text, or an object with a `string` property and optionally a `children` property). Passing an Array of objects, like `zoteroRoam.data.collections`, will not work.
Does that make sense ?

**Comment by mgdreamingstar** [comment]
Thank you very much for you patience. I'm not familiar with JS so hacking the template is a little painful.
Previously I'm debuging using Observable Notebook, however it's different with RR concerning datarequests.
Now everything is working as I expected, thanks again.

**Comment by mgdreamingstar** [comment]
Thank you very much for you patience. I'm not familiar with JS so hacking the template is a little painful.
Previously I'm debuging using Observable Notebook, however it's different with RR concerning datarequests.
Now everything is working as I expected, thanks again.
