### ISSUE TITLE
note html parsing issue

### ISSUE THREAD

**Issue by weihua-lu** [greenmeen/zotero-roam#9]
here's the note grabbed from api:
`"<div data-schema-version=\"3\"><p><span style=\"color: rgb(0, 0, 0)\"><span style=\"background-color: rgb(255, 255, 255)\">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec congue leo vel leo venenatis blandit. In hac habitasse platea dictumst.</span></span></p>\n</div>"`

when inserted into roam, there're extra span tags at end:
![image](https://user-images.githubusercontent.com/9002575/125735138-bab9bf62-1357-401e-8774-42defed821c6.png)

**Comment by greenmeen** [comment]
Just pushed a fix, it will be effective starting with the extension's next release.
Thanks for reporting!
